<?php

declare(strict_types=1);

namespace Xaraya\Kernel\Db\Dialect;

use PDO;
use Xaraya\Kernel\Db\Schema\Column;

final class Pgsql extends AbstractDialect
{
    public function name(): string
    {
        return 'pgsql';
    }

    public function onConnect(PDO $pdo): void
    {
        $pdo->exec("SET TIME ZONE 'UTC'");
    }

    public function listTablesSql(): string
    {
        return 'SELECT tablename FROM pg_tables WHERE schemaname = current_schema() ORDER BY tablename';
    }

    public function dropTableSql(string $table): string
    {
        return parent::dropTableSql($table) . ' CASCADE';
    }

    protected function boolLiteral(bool $value): string
    {
        return $value ? 'TRUE' : 'FALSE';
    }

    protected function incrementsSql(): string
    {
        return 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
    }

    protected function typeSql(Column $column): string
    {
        return match ($column->type) {
            'ulid' => 'CHAR(26)',
            'string' => 'VARCHAR(' . ($column->length ?? 255) . ')',
            'text' => 'TEXT',
            'json' => 'JSONB',
            'int' => 'INTEGER',
            'bigint' => 'BIGINT',
            'bool' => 'BOOLEAN',
            'datetime' => 'TIMESTAMP(0) WITHOUT TIME ZONE',
            default => throw new \InvalidArgumentException("Unknown column type '{$column->type}'"),
        };
    }
}
